///////////////////////////////////////////////////////////
//  CartonGanadorManager.cs
//  Implementation of the Class CartonGanadorManager
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:05:10 p.m.
//  Original author: Admin
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace BLBingo
{
    public class CartonGanadorManager:List<CartonGanador>
    {

        public CartonGanadorManager()
        {

        }

    } 
}//end CartonGanadorManager