///////////////////////////////////////////////////////////
//  CartonGanador.cs
//  Implementation of the Class CartonGanador
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:05:09 p.m.
//  Original author: Admin
///////////////////////////////////////////////////////////

namespace BLBingo
{
    public class CartonGanador : IListable 
    {
        private CartonBingo m_Carton;
        private eCodigoPremio m_Codigo;

        public CartonGanador()
        {

        }

        public CartonGanador(CartonBingo pCartonBingo, eCodigoPremio pCodigo)
        {
            m_Carton = pCartonBingo;
            m_Codigo = pCodigo;
        }

        public CartonBingo Carton
        {
            get
            {
                return m_Carton;
            }
            set
            {
                m_Carton = value;
            }
        }

        public eCodigoPremio Codigo
        {
            get
            {
                return m_Codigo;
            }
            set
            {
                m_Codigo = value;
            }
        }

        #region Miembros de IListable

        public string GetProperty(string pPropertyName)
        {
            string ret = "";
            switch (pPropertyName.ToLower())
            {
               case "nrocarton":
                   ret = this.Carton.NroCarton.ToString();
                   break;
                case "comprador":
                    ret = this.Carton.Comprador.NombreFormal;
                    break;
                case "vendedor":
                    ret = this.Carton.Vendedor.NombreFormal;
                    break;
                case "numeroscarton":
                    ret = this.Carton.Carton.Numeros.Serialize();   
                    break;
                default:
                    break;
            }
            return ret;
        }

        #endregion
    }
}