///////////////////////////////////////////////////////////
//  Comprador.cs
//  Implementation of the Class Comprador
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:05:05 p.m.
//  Original author: Paliza Martin
///////////////////////////////////////////////////////////

using DataBaseManager;
namespace BLBingo
{
    public class Comprador : Persona
    {
        public Comprador()
        {

        }
        
        public override void Save()
        {           
            long prevId = Id;//guardo el id antes de que me lo cambie basesave
            ParameterManager mParams = new ParameterManager();
            //agregar aca cualquier parametro de Vendedor, los de persona se llenan dentro del BaseSave.
            base.BaseSave(mParams);
            if (prevId == 0)//si era nuevo, ya esta guardado el registro en persona, ahora lo marco como vendedor
            {
                BaseDatos.DB.ExecuteSQLCommand("Insert Into Comprador (id) values(" + Id.ToString() + ")");
            }
        }
    }
}