///////////////////////////////////////////////////////////
//  StrategyA.cs
//  Implementation of the Class StrategyA
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:11:27 p.m.
//  Original author: tbrSoft
///////////////////////////////////////////////////////////

namespace BLBingo
{
    public class StrategyA : IStrategy
    {
        public StrategyA()
        {

        }
    
        /// <summary>
        /// Recibe una tList,Busca los cartones tales que todos sus numeros esten contenidos en pNumeros
        /// </summary>
        /// <param name="pNumeros"></param>
        public CartonGanadorManager ObtenerGanadores(CartonBingoManager pCartones, tList pNumeros)
        {
            CartonGanadorManager mCartonesGanadores = new CartonGanadorManager();
            CartonGanador cGanador = null;
            foreach (CartonBingo cartonB in pCartones)
            {
                if (EsGanador(cartonB, pNumeros))
                {
                    cGanador = new CartonGanador();
                    cGanador.Carton = cartonB;
                    cGanador.Codigo = eCodigoPremio.Bingo;
                    mCartonesGanadores.Add(cGanador );//agregar todos los cartones que sean ganadores
                }
            }
            
            return mCartonesGanadores;
        }

        private bool EsGanador(CartonBingo cartonB, tList pNumeros)
        {
            bool ret = true;
            if (cartonB.Estado != eEstadoCarton.Vendido)
            {
                return false;
            }
            foreach (int var in cartonB.Carton.Numeros  )
            {
                if (!pNumeros.Contains(var))
                {
                    ret = false;
                    break;
                }
            }
            return ret;
        }

    }//end StrategyA 
}