///////////////////////////////////////////////////////////
//  CompradorManager.cs
//  Implementation of the Class CompradorManager
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:05:11 p.m.
//  Original author: Admin
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Data;
using DataBaseManager;

namespace BLBingo
{
    public class CompradorManager:List<Comprador>
    {
        public CompradorManager()
        {

        }
               
        /// 
        /// <param name="pFilter"></param>
        public static CompradorManager FindByFilters(string pFilter)
        {   
            DataTable dt = BaseDatos.DB.ExecuteSQLCommand("Select * from CompradorPersona where nombre like '%"+pFilter+"%' OR apellido like '%"+pFilter+"%'");
            return Fill(dt);                 
        }

        /// 
        /// <param name="pIdComprador"></param>
        public static  Comprador FindById(long pIdComprador)
        {
            //TODO arreglar usando la funcion comprador.fillFrom...
            ParameterManager mParams = new ParameterManager();
            mParams.Add("Id", pIdComprador, true);             
            DataTable dt = BaseDatos.DB.ExecuteSelectCommand(MyTables.CompradorPersona, mParams);
                     
            return Fill(dt)[0];                       
        }

        private static CompradorManager Fill(DataTable pDT)
        {
            CompradorManager compradores = new CompradorManager();
            Comprador comprador;
            foreach (DataRow dr in pDT.Rows)
            {
                comprador = new Comprador();
                comprador.FillFromDataRow(dr);
                compradores.Add(comprador);
            }
            return compradores; 
        }
        
        internal static Comprador GetCompradorFromDR(DataRow dr, string p)
        {
            Comprador c= new Comprador();
            c.FillFromDataRow(dr, p);
            return c;
        }
    }//end CompradorManager 
}