///////////////////////////////////////////////////////////
//  IStrategy.cs
//  Implementation of the Interface IStrategy
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:11:24 p.m.
//  Original author: Paliza Martin
///////////////////////////////////////////////////////////

namespace BLBingo
{
    public interface IStrategy
    {

        /// <summary>
        /// Recibe una coleccion de cartones y una lista de numeros sorteados.
        /// </summary>
        /// <param name="pNumeros"></param>
        CartonGanadorManager ObtenerGanadores(CartonBingoManager pCartones, tList pNumeros);
    }//end IStrategy 
}