///////////////////////////////////////////////////////////
//  Vendedor.cs
//  Implementation of the Class Vendedor
//  Generated by Enterprise Architect
//  Created on:      07-Ago-2009 09:05:04 p.m.
//  Original author: Paliza Martin
///////////////////////////////////////////////////////////


using DataBaseManager;
namespace BLBingo
{
    public class Vendedor : Persona
    {
        public Vendedor()
        {
            
        }
        
        public override void Save()
        {
            long prevId=Id;//guardo el id antes de que me lo cambie basesave
            ParameterManager mParams = new ParameterManager();
            //agregar aca cualquier parametro de Vendedor, los de persona se llenan dentro del BaseSave.
            base.BaseSave(mParams);
            if (prevId == 0)//si era nuevo, ya esta guardado el registro en persona, ahora lo marco como vendedor
            {
                BaseDatos.DB.ExecuteSQLCommand("Insert Into Vendedor (id) values(" + Id.ToString() + ")");
            }            
        }

    }
}